name: Build

on:
  push:
    branches:
      - main
      - "bootstrap/**"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x86-64
          - os: windows-latest
            name: Windows x86-64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python MCPI client
        run: python -m pip install mcpi==1.2.1

      - name: Configure
        run: cmake -S . -B build -DMCPI_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
